# A list of Warp Route token configs
# These configs will be merged with the warp routes in the configured registry
# The input here is typically the output of the Hyperlane CLI warp deploy command
---
options: {}
tokens:
  - chainName: base
    standard: EvmHypSynthetic
    decimals: 18
    symbol: HOA
    name: Hex Orange Address
    addressOrDenom: '0x84B0b1EE6eef971105442Eb9Ab420F3DbB774b46'
    connections:
      - token: ethereum|pulsechain|0x50d03965Ed30de5d246BdDa18E7B10A8904B8CF1
  - chainName: pulsechain
    standard: EvmHypCollateral
    decimals: 18
    symbol: HOA
    name: Hex Orange Address
    addressOrDenom: '0x50d03965Ed30de5d246BdDa18E7B10A8904B8CF1'
    collateralAddressOrDenom: '0x7901a3569679AEc3501dbeC59399F327854a70fe'
    connections:
      - token: ethereum|base|0x84B0b1EE6eef971105442Eb9Ab420F3DbB774b46
  - chainName: base
    standard: EvmHypSynthetic
    decimals: 18
    symbol: COCK
    name: The Rise of Cock
    addressOrDenom: "0xC450f0887A94D1B2ad4b1b05734bEfe860919A2B"
    connections:
      - token: ethereum|mode|0x2fdd76fC5A8F6081E059DF76756E347f6B8278d8
      - token: ethereum|pulsechain|0x5DD749B87FA2e456482adb231FB9c2b0302A3027
      - token: ethereum|sei|0x86B1b88B2BBFe49999fA9A415270997ed1Bfd803
  - chainName: mode
    standard: EvmHypSynthetic
    decimals: 18
    symbol: COCK
    name: The Rise of Cock
    addressOrDenom: "0x2fdd76fC5A8F6081E059DF76756E347f6B8278d8"
    connections:
      - token: ethereum|base|0xC450f0887A94D1B2ad4b1b05734bEfe860919A2B
      - token: ethereum|pulsechain|0x5DD749B87FA2e456482adb231FB9c2b0302A3027
      - token: ethereum|sei|0x86B1b88B2BBFe49999fA9A415270997ed1Bfd803
  - chainName: pulsechain
    standard: EvmHypCollateral
    decimals: 18
    symbol: COCK
    name: The Rise of Cock
    addressOrDenom: "0x5DD749B87FA2e456482adb231FB9c2b0302A3027"
    collateralAddressOrDenom: "0x40b49a9e5B8E3CC137E9CA57A5F4382D1B3dF6FE"
    connections:
      - token: ethereum|base|0xC450f0887A94D1B2ad4b1b05734bEfe860919A2B
      - token: ethereum|mode|0x2fdd76fC5A8F6081E059DF76756E347f6B8278d8
      - token: ethereum|sei|0x86B1b88B2BBFe49999fA9A415270997ed1Bfd803
  - chainName: sei
    standard: EvmHypSynthetic
    decimals: 18
    symbol: COCK
    name: The Rise of Cock
    addressOrDenom: "0x86B1b88B2BBFe49999fA9A415270997ed1Bfd803"
    connections:
      - token: ethereum|base|0xC450f0887A94D1B2ad4b1b05734bEfe860919A2B
      - token: ethereum|mode|0x2fdd76fC5A8F6081E059DF76756E347f6B8278d8
      - token: ethereum|pulsechain|0x5DD749B87FA2e456482adb231FB9c2b0302A3027  